name: mymaptest
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  mapbox_gl:
    git:
      url: https://github.com/KumaloWilson/maps.git
  geolocator: ^13.0.3
  permission_handler: ^11.4.0
  geocoding: ^3.0.0
  mapbox_search: any
  dio: ^5.8.0+1
  google_fonts: ^6.2.1
  fl_chart: ^0.70.2
  flutter_slidable: ^4.0.0
  font_awesome_flutter: ^10.8.0
  flutter_flip_card: ^0.0.6
  get: ^4.7.2
  shared_preferences: ^2.5.2
  logger: ^2.5.0
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  loading_animation_widget: ^1.3.0
  pinput: ^5.0.1
  cloud_firestore: ^5.6.5
  flutter_svg: ^2.0.17
  intl: ^0.20.2
  uuid: ^4.5.1
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^19.0.0
  firebase_storage: ^12.4.4
  image_picker: ^1.1.2
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  flutter_tts: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/icons/
  - assets/images/
  - assets/cache.db
